# Q10.Create a function that takes 2 positive integers in form of a string as an input, and outputs the
# sum (also as a string):
# "4", "5" --> "9"
# "34", "5" --> "39"
# Notes:
# If either input is an empty string, consider it as zero.



# def my_function():
#     a=(input("enter the number"))
#     b=(input("enter the number"))
#     c=int(a)+int(b)
#     d=str(c)
#     print(type(a))
#     print(type(b))
#     print(d)
#     print(type(d))
# my_function()