# Q25. Given a list of numbers, write a Python program to count positive and negative numbers in a List using
# function.
# Example:
# list1 = [2, -7, 5, -64, -14]
# Output: pos = 2, neg = 3


# def my_function():
#     a=[2,-7,5,-64,-14]
#     i=0
#     count=0
#     count1=0
#     while i<len(a):
#         if a[i]>0:
#             count=count+1
#         else:
#             count1=count1+1
#         i=i+1
#     print("positive number",count)
#     print("negative number",count1)
# my_functiprint(5+6%10)



# SHIVANI'S QUESTION

# def my_function(a,b):
#     c=a+b
#     if c>=15 and c<=20:
#         return 20
#     else:
#         return c
# print(my_function(15,17))

