# Q39. Your task is to make two functions, max and min (maximum and minimum in PHP and
# Python, maxi and mini in Julia) that take a(n) array/vector of integers list as input and outputs,
# respectively, the largest and lowest number in that array/vector.
# #Examples:-
# maximun([4,6,2,1,9,63,-134,566]) returns 566
# minimun([-52, 56, 30, 29, -54, 0, -110]) returns -110
# maximun([5]) returns 5.
# minimun([42, 54, 65, 87, 0]) returns 0.


# def my_function():
#     n=[4,6,2,1,9,63,-134,566]
#     i=0
#     max=n[0]
#     while i<len(n):
#         if n[i]>max:
#           max=n[i]
#         i=i+1
#     return max
# print(my_function())

# def my_function():
#     n=[-52, 56, 30, 29, -54, 0, -110]
#     i=0
#     min=n[0]
#     while i<len(n):
#         if n[i]<min:
#           min=n[i]
#         i=i+1
#     return min
# print(my_function())

# def my_function():
#     n=[5]
#     i=0
#     max=n[0]
#     while i<len(n):
#         if n[i]>max:
#           max=n[i]
#         i=i+1
#     return max
# print(my_function())


