# Q48. Two numbers are entered through the keyboard. Write a flowchart to find the value of the
# raised to the power of another.
# Sample Input
# 3
# 4
# Sample Output
# 81 (3x3x3x3)
# first number
# Sample Input
# 5
# 3
# Sample Output
# 125 (5x5x5)
# Sample Input
# 6
# 7
# Sample Output
# 279936 (6x6x6x6x6x6x6)




def my_function():
    a=int(input("enter the base"))
    b=int(input("enter the power"))
    print(a**b)
my_function()
