# Q9.Write a Python program to generate and print a list of first and last 5 elements where
# the values are square of numbers between 1 and 30 (both included).
# Output :-([1, 4, 9, 16, 25], [676, 729, 784, 841, 900]).


# def my_function():
#     i=0
#     l=[]
#     l1=[]
#     while i<=30:
#         if i>0 and i<6 :
#             l.append(i**2)
#         elif i>25 and i<=30:
#             l1.append(i**2)
#         i=i+1
#     print(l,l1)
# my_function()



