# n=int(input("how many elements you want in your list?"))
# i=0
# b=[]
# while i<n:
#     i=i+1
#     a=int(input("enter the number"))
#     b.append(a)
# print(b)
# i=0
# sum=0
# while i<len(b):
#     sum=sum+b[i]
#     i=i+1
# print(sum)



# a=[]
# size=int(input("enter the size of list"))
# for i in range(size):
#     val=int(input("enter numbers"))
#     a.append(val)
#     print(a)
# i=0
# sum=0
# while i<len(a):
#     sum=sum+a[i]
#     i=i+1
# print(sum)

# def my_function():
#     a=int(input("enter the number"))
#     i=1
#     while i<=a:
#         if a%i==0:
#             print(i)
#         i=i+1
# my_function()

# using return factorial
# def fact(num):
#     if num==1:
#         return 1
#     return num*fact(num-1)
# print(fact(5))


# sum of nested list:-
# def my_function():
#     a=[[1,2,3],[1,2,3],[1,2,3]]
#     i=0
#     sum=0
#     while i<len(a):
#         j=0
#         while j<len(a[i]):
#             sum=sum+a[i][j]
#             j=j+1
#         i=i+1
#     print(sum)
# my_function()

# def my_function():
#     a=[1,2,3,4,5,6,6,7]
#     b=[]
#     n=int(input("enter the number"))
#     i=0
#     while i<len(a):
#         if a[i]>n:
#             b.append(a[i])
#         i=i+1
#     print(b)
# my_function()


