# Q1 . You have to print the largest value out of the given list using the max function.

# def max():
#     n=[3,5,7,34,2,89,2,5]
#     i=0
#     max=0
#     while i<len(n):
#         if n[i]>max:
#             max=n[i]
#         i=i+1
#     print(max)
# max()


# n=[3,5,7,34,2,89,2,5]
# print(len(n))



# Q2. You have to print the sum of the elements of the given list by using the sum function..............


# def sum():
#     numbers = [1, 2, 3, 4, 5,6]
#     sum=0
#     i=0
#     while i<len(numbers):
#         sum=sum+numbers[i]
#         i=i+1
#     print(sum)
# sum()

# numbers = [1, 2, 3, 4, 5,6]
# print(sum(numbers))


# Q3. Using sort function sort the given list.......


# def sort():
#     a = [6, 8, 4, 3, 9, 56, 0, 34, 7, 15]
#     a.sort()
#     print(a)
# sort()



# Q4. By using reverse function print the reverse order of the list..................


# def reverse():
#     reverse_list = ["Z", "A", "A", "B", "E", "M", "A", "R", "D"]
#     reverse_list .reverse()
#     print(reverse_list)
# reverse()


# Q5. Use the min function and find the minimun value of the list.


# def minimum():
# list=[8,6,4,8,4,50,2,7]
#     min_value=min(list)
#     print(min_value)
# minimum()



# def minimum():
#     list = [8, 6, 4, 8, 4, 50, 2, 7]
#     print(min(list))
# minimum()




