# Write a function named function_print_lines which takes 2 strings, and prints them in the following manner.

# If we give these 2 arguments - "My name is Rishabh." and "I am the co-founder of NavGurukul"
# we will get the following output:


def function_print():
    print("My name is Rishibh..")
    print("I am co-founder of Navgurukul.")
function_print()


def function_print_lines():
    a="My name is Rishabh.."
    b="i am the co-founder of NavGurukul."
    print(a)
    print(b)
function_print_lines()