# Question 1
# def sum()
#  print(12+13)
# sum()

def sum():
    print(12+13)
sum()

# Question 2
# daf welcome():
#  print("Welcome to function")
# welcome()

def welcome():
    print("Welcome to function")
welcome()


# Question 3
# isEven()
# def isEven():
#  if(12%2==0):
#   print("Even Number")
#  else:
#   print("Old Number")

def isEven():
    if(12%2==0):
        print("Even Number")
    else:
        print("Old Number")
isEven() 


