# def calculator(number_x,number_y,operation):
#     if operation=="add":
#         print(number_x+number_y)
#     elif operation=="subtract":
#         print(number_x-number_y)
#     elif operation=="multiplication":
#         print(number_x*number_y)
#     elif operation=="divide":
#         print(number_x/number_y)
# calculator(3,5,"add")
# calculator(3,5,"subtrac;t")
# calculator(3,5,"multiplication")
# calculator(3,5,"operation")







# def calculator(number_x,number_y,operation):
#     if operation=="add":
#         number_1=number_x+number_y
#         print(number_1)
#     elif operation=="subtract":
#         number_2=(number_x-number_y)
#         print(number_2)
#     elif operation=="multiplication":
#         number_3=(number_x*number_y)
#         print(number_3)
#     elif operation=="divide":
#         number_4=(number_x/number_y)
#         print(number_4)
# calculator(3,5,"add")
# calculator(3,5,"subtrac;t")
# calculator(3,5,"multiplication")
# calculator(3,5,"divide")

# def calculator(operation):
#     a=int(input("enter the number"))
#     b=int(input("enter the number"))
#     if operation=="+":
#        print(a+b)
#     elif operation=="-":
#        print(a-b)
#     elif operation=="*":
#        print(a*b)
#     elif operation=="/":
#         print(a/b)
# calculator("+")
# calculator("-")
# calculator("*")
# calculator("/")

# def list_change(number1_list,number2_list):
#     a=[]
#     i=0
#     j=0
#     while i<len(number1_list):
#         a.append(number1_list[i]*number2_list[j])
#         i=i+1
#         j=j+1
#     print(a)
# list_change([5,10,50,20],[2,20,3,5])
