# Question 1 (Part 1)
# Write a function named ask_question which will print the text "Once".
# Code Example
#write function here
# Who is the founder of Facebook?
# - Mark Zuckerberg
# - Bill Gates
# - Steve Jobs
# - Larry Page
# Then call this function 5 times and get this text printed 5 times.


#  def ask_question():
#         print('Who is the founder of Facebook?')

#         print('- Mark Zuckerberg')
#         print('- Bill Gates')
#         print('- Steve Jobs')
#         print('- Larry Page') 
# ask_question()
# ask_question()
# ask_question()
# ask_question()
# ask_question()

# Question 1 (Part 2)
# Then using the while loop wrote the code to call this function 100 times.


# def ask_question():
#     i=0
#     while i<=100:
#         print("who is the founder of facebook?")
        
#         print('- mark zuckerberg')
#         print('- bill gates')
#         print('- steve jobs')
#         print('- larry')
#         i=i+1
# ask_question()

