# Question 3
# Create a function which takes 3 arguments(all integers) and prints their sum and average as shown below.
# Input:-
# Enter first number :-3
# Enter second number :-4
# Enter third number:-5
# Output :-
# Sum of three numbers :-12
# Average of three numbers :-4





def my_function(a,b,c):
    print("sum of three numbers",a+b+c)
    print("average of three numbers",a+b+c/3)
my_function(2,3,4)

def my_function():
    a=int(input("enter the number"))
    b=int(input("enter the second number"))
    c=int(input("enter the third number"))
    print("sum of three numbers",a+b+c)
    def my_function2():
        print("average of three numbers",a+b+c/3)
    my_function2()
my_function()


